
version: 2

models:
  - name: cleaned_sales_data
    description: "Cleandes slaes listings data"
    columns:
      - name: artikelnummer
        description: "The primary key for this table, artikel nummer from Thomann"
        tests:
          - not_null
      - name: date
        description: "When was this listing observed"
        tests:
          - not_null
      - name: preis
        description: "Price of Guitar"
        tests:
          - not_null
      - name: verkaufsrang
        description: "Internal Thomann sales rank"
        tests:
          - not_null